const GET_ALL_RECIPE= "GET_ALL_RECIPE";
const GET_ALL_DIET = "GET_ALL_DIET";
const FILTER_BY_DIET = "FILTER_BY_DIET";
const DETAIL = "DETAIL";
const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY";
const ORDER_SCORE = "ORDER_SCORE ";
const GET_BY_NAME ="GET_BY_NAME"
module.exports ={
    GET_ALL_RECIPE,
    GET_ALL_DIET,
    FILTER_BY_DIET,
    DETAIL,
    ORDER_ALPHABETICALLY,
    ORDER_SCORE,
    GET_BY_NAME
}